name: tsf-env
channels:
  - conda-forge
dependencies:
  - ipykernel=6.29.5
  - ipython=8.30.0
  - jupyterlab=4.3.3
  - matplotlib=3.9.4
  - numpy=2.2.0
  - pandas=2.2.3
  - plotly=5.24.1
  - prophet=1.1.6
  - scikit-learn=1.6.0
  