name: tsf-env
channels:
  - conda-forge
dependencies:
  - ipykernel=6.29.5
  - ipython=8.30.0
  - joblib=1.4.2
  - jupyterlab=4.3.3
  - matplotlib=3.9.4
  - numpy=2.2.0
  - pandas=2.2.3
  - prophet=1.1.6
  - python=3.11.11
  - scikit-learn=1.6.0
